### Pandas (stands for Python Data Analysis) 
is an open-source software library designed for data manipulation and analysis.

In [1]:
import pandas as pd

### Understanding a DataFrame
### Creating data
There are two core objects in pandas: the DataFrame and the Series.

#### DataFrame
A DataFrame is a table. It contains an array of individual entries, each of which has a certain value. 
Each entry corresponds to a row (or record) and a column.

For example, consider the following simple DataFrame:

In [2]:
df = pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

In [3]:
df

   Yes   No
0   50  131
1   21    2

In [4]:
import pandas as pd
students = {
    "Roll_No": [101, 102, 103, 104, 105,106],
    "Name": ["Aman", "Priya", "Rahul", "Sneha", "Vikas","Samar"],    
    "Department": ["BCA", "BCA", "MCA", "BCA", "MCA","BCA"],   
    "Marks": [82, 91, 76, 88, 69,92],
    "Attendance": [92, 95, 87, 90, 85,99]
}

df = pd.DataFrame(students)
df

   Roll_No   Name Department  Marks  Attendance
0      101   Aman        BCA     82          92
1      102  Priya        BCA     91          95
2      103  Rahul        MCA     76          87
3      104  Sneha        BCA     88          90
4      105  Vikas        MCA     69          85
5      106  Samar        BCA     92          99

In [5]:
# Shows the first 5 rows of your dataset to preview it.
df.head()

   Roll_No   Name Department  Marks  Attendance
0      101   Aman        BCA     82          92
1      102  Priya        BCA     91          95
2      103  Rahul        MCA     76          87
3      104  Sneha        BCA     88          90
4      105  Vikas        MCA     69          85

In [6]:
# Gives total dimensions as a tuple (number of rows, number of columns).
df.shape

(6, 5)

In [7]:
# Lists the names of all columns in the dataset.
df.columns

Index(['Roll_No', 'Name', 'Department', 'Marks', 'Attendance'], dtype='object')

In [8]:
# Calculates the average value
df["Marks"].mean()

np.float64(83.0)

In [9]:
# Lists the data type (like integers, floats, or text) of every column.
df.dtypes

Roll_No        int64
Name          object
Department    object
Marks          int64
Attendance     int64
dtype: object

### Lab 1 : Create a DataFrame of 5 books having:
Book_ID 

Title 

Author 

Price 

Pages 

#### Answer following Question:

1. Display the first five records.
2. Display the last five records.
3. Find the number of rows and columns.
4. Show the column names.
5. Display data types.
6. Find the average of one numeric column.
7. Find the maximum and minimum values of one numeric column.

In [10]:
df["Name"]

0     Aman
1    Priya
2    Rahul
3    Sneha
4    Vikas
5    Samar
Name: Name, dtype: object

In [11]:
df["Name"]

0     Aman
1    Priya
2    Rahul
3    Sneha
4    Vikas
5    Samar
Name: Name, dtype: object